### ISSUE TITLE
Support for Siemens Biograph mCT Scanner

### ISSUE THREAD

**Issue by hrashidykanan** [r-santo/openSSS#1]
Dear developers,
Thank you very much for this interesting and helpful implementation.

I am actively engaged in PET image reconstruction and specifically utilizing the Siemens Biograph mCT 1104 scanner for our clinical data. My objective is to integrate a scatter estimation algorithm into our reconstruction pipeline. I am interested to explore the potential compatibility of your implementation with our scanner. If such compatibility exists, I would greatly appreciate it if you could provide me with some guidance or insights.

Your assistance is highly anticipated.

**Comment by r-santo** [comment]
Dear user,

Thank you for reaching out and your interest in openSSS. We have developed openSSS to be compatible with custom scanners, which you can configure through the parameters reported in the _Example.m_ file and the definition of the position of every detector in the scanner, as exemplified in that same file.

Additionally, you must have access to the raw data of the scanner, in order to perform scaling of the scatters. For clinical system, it is usually required for one to have a research agreement with the scanner's vendor. 

Can you confirm you have access to all the required information? From that, we can provide more specific guidance.

**Comment by hrashidykanan** [comment]
Thank you very much for your quick reply.

Yes, I confirmed that we have access to all the mentioned information.

I tried to run the Example.m file. However, it crashed by "out of Memory" error. Even, I tried to prevent this error by changing "DesiredDimensions" variable to [90, 90 ,48]/3. But, I still have the crashing problem. Could you please help me on this matter.
Also, I would appreciate it if you could provide me with more specific guidance.

**Comment by r-santo** [comment]
I have investigated the problem and although I cannot reproduce it, I'm believe I know the origin. The example file is based on a large system with a high number of crystals (80 rings each with 760 detectors), translating into a large number of LORs. This only gets more aggravated the more TOF bins are defined. Therefore, the memory requirements for such system can be quite demanding on the current implementation.

To quickly solve your problem, just so you get an idea of how the library works, I suggest you significantly change the number of TOF bins, for example to 2 or 3. 
To avoid this problem for other users when trying out this library, I will soon change the example system to a much smaller design: a toy model that makes it easy to understand how to setup custom geometries and how to link it with other libraries.

With the current implementation, custom geometries are defined in a matrix of shape [a,b,c], where a is the number of rings, b is the number of detectors and c is the number of dimensions (always 3). So for every detector, you need to specify its coordinates.

**Comment by hrashidykanan** [comment]
Again, thank you very much for your response and the solutions you provided.

As part of my experience running the Example.m, I clear "SinogramsInerpolatedCurrentBin" variable (because it is saved) just by adding a simple "clear SinogramsInerpolatedCurrentBin" command after row 435 in "InterpolatedSinograms" function which is in "SingleScatterSimulationTOF.m" function. Now, my out of memory problem related to "SingleScatterSimulationTOF.m" has been fixed and Single Scatter Simulations for all the bins are created. However, there is still a memory issue for "BackProjectionScatterRandFit" function. Anyway, I think, I would be able to run the example with the solutions you mentioned.

Looking forward to the further changes in this example.

Thank you very much.

**Comment by r-santo** [comment]
As promised, a new example geometry has been added to the repository: a toy scanner that is substantially smaller (less rings, less detectors per ring) than the previously provided implementation. This should make it easier to run the example script on typical desktop computers, without memory issues.
